### ISSUE TITLE
Support non-basic quorums

### ISSUE THREAD

**Issue by uluyol** [goelayu/NSDi-17#4]
Support needs to be added for non-basic quorums. You probably want an abstract quorum system class and pass in all replica latencies and have that determine the latency for any given request.

**Comment by uluyol** [comment]
I can implement the non-basic quorums once you have the structure there. That's tricky enough that I should probably do it.

**Comment by goelayu** [comment]
Resolved by [this](https://github.com/goelayu/NSDi-17/commit/9e0db684512994de3a3779a3d5fa5b2ba2b7f053) commit. 

A lot of code can be refactored for better readability, but right now I'm just focusing on getting this done as soon as possible. Let me know if you have some specific concerns about the code. @uluyol
