### ISSUE TITLE
Import all formulation config types

### ISSUE THREAD

**Issue by uluyol** [goelayu/NSDi-17#8]
Formulations of interest:
* fixautosplit [basic quorums, no flexible paxos]
* flexbasic [basic quorums, flexible paxos]
* flexgen [specified quorums, flexible paxos]
* flexgenexp [specified req-per-split quorums, flexible paxos]

For fixautosplit & flexbasic, number of splits per replica DC is 1.
For the others, read out from SPLITS_dc variables.
For others, read out quorums members based on R_fe_dc or W_fe_dc variables.

It's safe to infer the formulation type based on the name of the file. It will be prefixed with that name followed by a dash.

**Comment by goelayu** [comment]
Resolved by [this](https://github.com/goelayu/NSDi-17/commit/146f2eef508adc25082711d8d768f42c50d3ac38) commit. Kindly review @uluyol
